language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then sudo apt-get install -y --force-yes libgeoip-dev; fi'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then pecl install geoip; fi'
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

script: phpunit --coverage-text
